// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import OnClickUploadController from "./on_click_upload_controller.js"
application.register("on_click_upload", OnClickUploadController)
