// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AutouploadController from "./autoupload_controller.js"
application.register("autoupload", AutouploadController)

import DropzoneController from "./dropzone_controller.js"
application.register("dropzone", DropzoneController)
