version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es01
    environment:
      'bootstrap.memory_lock': ${ELASTIC_SEARCH_MEMORY_BLOCK}
      'node.name': es01
      'discovery.type': single-node

      ES_JAVA_OPTS: ${ELASTIC_JAVA_OPTIONS}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:$PWD/tmp/elasticsearch/data
      - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana_ui
    volumes:
      - kibana_volume:/usr/share/kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
      XPACK_SECURITY_ENABLED: 'true'
      ELASTICSEARCH_USERNAME: ${KIBANA_USER}
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    depends_on:
      - es01
    networks:
      - elastic
    ports:
      - 5601:5601

volumes:
  data01:
    driver: local
  kibana_volume:
    driver: local

networks:
  elastic:
    driver: bridge
